hub:
  container_name: selenium-hub

  image: selenium/hub:latest

  ports:
   - "4444:4444"

chrome:
   
  image: selenium/node-chrome:latest

  ports:
   - "5900"

  #volumes:
  #- c:\temp\oneToOne\:/temp/oneToOne/

  links:
   - hub